# bactrack/38g.yaml

### GPU-accelerated conda environment
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
# conda package specification
# https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html

### Changelog:

# 2020-11-06
# - cleaned up based on cpu env

#-------------------------------------------------------------------------------

# CUDA 10.1 requirement: gated by tensorflow, so ensure jax and pytorch follow.

## Additions not found in cpu environment:
# - rapidsai https://rapids.ai/start.html#get-rapids

# For dataloading and munging in jax
# https://github.com/tensorflow/datasets
# New v4.0.0 in October with new API, dataset-as-folder
# Look out for breaking changes, e.g. tfds.as_numpy()
# defaults has very old version v1.x series, so use pip

### GPU-enabled JAX
# https://github.com/google/jax#installation
# Requires a system CUDA installation at /usr/local/cuda-X.X
# 1. Need to run 'sudo apt install nvidia-cuda-toolkit'
# This install cuda 10.1, inspect files installed with 'dpkg -L nvidia-cuda-toolkit'
# cuda is installed at /usr/lib/cuda
# 2. So we symlink:
# sudo ln -s /usr/lib/cuda /usr/local/cuda-10.1
# and restart jupyter kernel
# https://github.com/google/jax/issues/4452
# TODO: figure if we can use conda's cudatoolkit?

#-------------------------------------------------------------------------------
name: 38g
channels:
  - rapidsai
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - anaconda
  - altair
  - black
  - blas=*=mkl
  - cudatoolkit=10.1
  - dvc
  - isort
  - jedi>=0.17
  - jupyterlab
  - jupytext
  - natsort
  - nodejs
  - papermill
  - pip
  - pre-commit
  - pyarrow
  - pyvips
  - pytest
  - pytorch
  - rapids=0.16
  - scikit-image
  - scikit-learn
  - shellcheck
  - torchvision
  - torchaudio
  - zarr
  - pip:
    - --use-feature=2020-resolver
    - aicspylibczi
    - aicsimageio
    - czifile
    - jax
    - jaxlib==0.1.56+cuda101
    - -f https://storage.googleapis.com/jax-releases/jax_releases.html
    - tensorflow
    - tensorflow-datasets
    - nb_black
    - tfrecorder

# https://github.com/dnanhkhoa/nb_black
# https://github.com/google/tensorflow-recorder